### ISSUE TITLE
repository didn't get created properly

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/wesnoth-map-diff#1]
I was trying to make a clone of just the wesnoth-map-diff subdirectory of the main wesnoth repo by using the `git_export_campaign` script: https://github.com/cooljeanius/wesnoth/commit/ac6def8dad218b4d2c34d395dbc3b91ad7db6e51
However, it doesn't seem to have worked properly: instead of exporting the entire directory, it just exported the `COPYING.txt` file.

**Comment by macabeus** [comment]
I always forget how to split a folder from a git repository.
When I need to do it, I always follow the GitHub doc: https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by cooljeanius** [comment]
> I always forget how to split a folder from a git repository. When I need to do it, I always follow the GitHub doc: [docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository)
> 
> Did you try to do it?

Hm, looks like I'll need to get `git-filter-repo` installed and set up first...

**Comment by cooljeanius** [comment]
ok I think I've got it right now, as of [e93b41c](https://github.com/cooljeanius/wesnoth-map-diff/commit/e93b41ceaa5c81e49cc573ad1e97b6d73e603520)...
